import type { ThingInfo } from '../types';

export const THINGS: Record<number, ThingInfo> = {
  1:    { name: 'Player 1 Start',   cat: 'player',  r: 16 },
  2:    { name: 'Player 2 Start',   cat: 'player',  r: 16 },
  3:    { name: 'Player 3 Start',   cat: 'player',  r: 16 },
  4:    { name: 'Player 4 Start',   cat: 'player',  r: 16 },
  11:   { name: 'Deathmatch Start', cat: 'player',  r: 16 },
  3004: { name: 'Zombieman',        cat: 'enemy',   r: 20 },
  9:    { name: 'Shotgun Guy',      cat: 'enemy',   r: 20 },
  3001: { name: 'Imp',             cat: 'enemy',   r: 20 },
  3002: { name: 'Demon',           cat: 'enemy',   r: 30 },
  58:   { name: 'Spectre',         cat: 'enemy',   r: 30 },
  3005: { name: 'Cacodemon',       cat: 'enemy',   r: 31 },
  3003: { name: 'Baron of Hell',   cat: 'enemy',   r: 24 },
  3006: { name: 'Lost Soul',       cat: 'enemy',   r: 16 },
  16:   { name: 'Cyberdemon',      cat: 'enemy',   r: 40 },
  7:    { name: 'Spider Mastermind',cat: 'enemy',   r: 128},
  65:   { name: 'Chaingun Guy',    cat: 'enemy',   r: 20 },
  64:   { name: 'Arch-Vile',       cat: 'enemy',   r: 20 },
  66:   { name: 'Revenant',        cat: 'enemy',   r: 20 },
  67:   { name: 'Mancubus',        cat: 'enemy',   r: 48 },
  68:   { name: 'Arachnotron',     cat: 'enemy',   r: 64 },
  69:   { name: 'Hell Knight',     cat: 'enemy',   r: 24 },
  71:   { name: 'Pain Elemental',  cat: 'enemy',   r: 31 },
  84:   { name: 'Wolfenstein SS',  cat: 'enemy',   r: 20 },
  2005: { name: 'Chainsaw',        cat: 'weapon',  r: 10 },
  2001: { name: 'Shotgun',         cat: 'weapon',  r: 10 },
  82:   { name: 'Super Shotgun',   cat: 'weapon',  r: 10 },
  2002: { name: 'Chaingun',        cat: 'weapon',  r: 10 },
  2003: { name: 'Rocket Launcher', cat: 'weapon',  r: 10 },
  2004: { name: 'Plasma Rifle',    cat: 'weapon',  r: 10 },
  2006: { name: 'BFG 9000',        cat: 'weapon',  r: 10 },
  2007: { name: 'Clip',            cat: 'ammo',    r: 10 },
  2048: { name: 'Box of Bullets',  cat: 'ammo',    r: 10 },
  2008: { name: 'Shells',          cat: 'ammo',    r: 10 },
  2049: { name: 'Box of Shells',   cat: 'ammo',    r: 10 },
  2010: { name: 'Rocket',          cat: 'ammo',    r: 10 },
  2046: { name: 'Box of Rockets',  cat: 'ammo',    r: 10 },
  2047: { name: 'Energy Cell',     cat: 'ammo',    r: 10 },
  17:   { name: 'Energy Cell Pack',cat: 'ammo',    r: 10 },
  2014: { name: 'Health Bonus',    cat: 'health',  r: 10 },
  2011: { name: 'Stimpack',        cat: 'health',  r: 10 },
  2012: { name: 'Medikit',         cat: 'health',  r: 10 },
  2013: { name: 'Soulsphere',      cat: 'health',  r: 10 },
  83:   { name: 'Megasphere',      cat: 'health',  r: 10 },
  2015: { name: 'Armor Bonus',     cat: 'armor',   r: 10 },
  2018: { name: 'Green Armor',     cat: 'armor',   r: 10 },
  2019: { name: 'Blue Armor',      cat: 'armor',   r: 10 },
  5:    { name: 'Blue Keycard',    cat: 'key',     r: 10 },
  13:   { name: 'Red Keycard',     cat: 'key',     r: 10 },
  6:    { name: 'Yellow Keycard',  cat: 'key',     r: 10 },
  40:   { name: 'Blue Skull Key',  cat: 'key',     r: 10 },
  38:   { name: 'Red Skull Key',   cat: 'key',     r: 10 },
  39:   { name: 'Yellow Skull Key',cat: 'key',     r: 10 },
  2022: { name: 'Invulnerability', cat: 'powerup', r: 10 },
  2023: { name: 'Berserk',         cat: 'powerup', r: 10 },
  2024: { name: 'Invisibility',    cat: 'powerup', r: 10 },
  2025: { name: 'Radiation Suit',  cat: 'powerup', r: 10 },
  2026: { name: 'Computer Map',    cat: 'powerup', r: 10 },
  2045: { name: 'Light Goggles',   cat: 'powerup', r: 10 },
  // Decorations & obstacles
  2035: { name: 'Barrel',             cat: 'decor', r: 10 },
  70:   { name: 'Burning Barrel',     cat: 'decor', r: 10 },
  43:   { name: 'Burnt Tree',         cat: 'decor', r: 16 },
  54:   { name: 'Brown Tree',         cat: 'decor', r: 16 },
  2028: { name: 'Floor Lamp',         cat: 'decor', r: 16 },
  85:   { name: 'Tall Techno Lamp',   cat: 'decor', r: 16 },
  86:   { name: 'Short Techno Lamp',  cat: 'decor', r: 16 },
  34:   { name: 'Candle',             cat: 'decor', r: 16 },
  35:   { name: 'Candelabra',         cat: 'decor', r: 16 },
  44:   { name: 'Tall Blue Torch',    cat: 'decor', r: 16 },
  45:   { name: 'Tall Green Torch',   cat: 'decor', r: 16 },
  46:   { name: 'Tall Red Torch',     cat: 'decor', r: 16 },
  55:   { name: 'Short Blue Torch',   cat: 'decor', r: 16 },
  56:   { name: 'Short Green Torch',  cat: 'decor', r: 16 },
  57:   { name: 'Short Red Torch',    cat: 'decor', r: 16 },
  48:   { name: 'Tall Techno Column', cat: 'decor', r: 16 },
  30:   { name: 'Tall Green Pillar',  cat: 'decor', r: 16 },
  32:   { name: 'Short Green Pillar', cat: 'decor', r: 16 },
  31:   { name: 'Tall Red Pillar',    cat: 'decor', r: 16 },
  33:   { name: 'Short Red Pillar',   cat: 'decor', r: 16 },
  36:   { name: 'Pillar w/ Heart',    cat: 'decor', r: 16 },
  37:   { name: 'Pillar w/ Skull',    cat: 'decor', r: 16 },
  47:   { name: 'Brown Stump',        cat: 'decor', r: 16 },
  41:   { name: 'Evil Eye',           cat: 'decor', r: 16 },
  42:   { name: 'Floating Skull',     cat: 'decor', r: 16 },
  10:   { name: 'Bloody Mess 1',      cat: 'gore',  r: 16 },
  12:   { name: 'Bloody Mess 2',      cat: 'gore',  r: 16 },
  24:   { name: 'Pool of Blood',      cat: 'gore',  r: 16 },
  27:   { name: 'Pole w/ Skull',      cat: 'gore',  r: 16 },
  28:   { name: 'Skewer w/ Heads',    cat: 'gore',  r: 16 },
  29:   { name: 'Pile of Skulls',     cat: 'gore',  r: 16 },
  25:   { name: 'Impaled Body',       cat: 'gore',  r: 16 },
  26:   { name: 'Twitching Body',     cat: 'gore',  r: 16 },
  49:   { name: 'Hanging Body 1',     cat: 'gore',  r: 16 },
  50:   { name: 'Hanging Body 2',     cat: 'gore',  r: 16 },
  51:   { name: 'Hanging Body 3',     cat: 'gore',  r: 16 },
  52:   { name: 'Hanging Body 4',     cat: 'gore',  r: 16 },
  53:   { name: 'Hanging Body 5',     cat: 'gore',  r: 16 },
  73:   { name: 'Hanging Body 6',     cat: 'gore',  r: 16 },
  74:   { name: 'Hanging Body 7',     cat: 'gore',  r: 16 },
  75:   { name: 'Hanging Body 8',     cat: 'gore',  r: 16 },
  76:   { name: 'Hanging Body 9',     cat: 'gore',  r: 16 },
  77:   { name: 'Hanging Body 10',    cat: 'gore',  r: 16 },
  78:   { name: 'Hanging Body 11',    cat: 'gore',  r: 16 },
  79:   { name: 'Hanging Body 12',    cat: 'gore',  r: 16 },
  15:   { name: 'Dead Marine',        cat: 'gore',  r: 16 },
  18:   { name: 'Dead Zombieman',     cat: 'gore',  r: 16 },
  19:   { name: 'Dead Shotgun Guy',   cat: 'gore',  r: 16 },
  20:   { name: 'Dead Imp',           cat: 'gore',  r: 16 },
  21:   { name: 'Dead Demon',         cat: 'gore',  r: 16 },
  22:   { name: 'Dead Cacodemon',     cat: 'gore',  r: 16 },
  23:   { name: 'Dead Lost Soul',     cat: 'gore',  r: 16 },
  14:   { name: 'Teleport Landing',   cat: 'decor', r: 16 },
  88:   { name: 'Boss Brain',         cat: 'enemy', r: 16 },
  89:   { name: 'Spawn Shooter',      cat: 'enemy', r: 16 },
  87:   { name: 'Spawn Spot',         cat: 'enemy', r: 16 },
};

export const THING_SPRITE: Record<number, string> = {
  1: 'PLAY', 2: 'PLAY', 3: 'PLAY', 4: 'PLAY', 11: 'PLAY',
  3004: 'POSS', 9: 'SPOS', 3001: 'TROO', 3002: 'SARG', 58: 'SARG',
  3005: 'HEAD', 3003: 'BOSS', 3006: 'SKUL', 16: 'CYBR', 7: 'SPID',
  65: 'CPOS', 64: 'VILE', 66: 'SKEL', 67: 'FATT', 68: 'BSPI',
  69: 'BOS2', 71: 'PAIN', 84: 'SSWV',
  2005: 'CSAW', 2001: 'SHOT', 82: 'SGN2', 2002: 'MGUN',
  2003: 'LAUN', 2004: 'PLAS', 2006: 'BFUG',
  2007: 'CLIP', 2048: 'AMMO', 2008: 'SHEL', 2049: 'SBOX',
  2010: 'ROCK', 2046: 'BROK', 2047: 'CELL', 17: 'CELP',
  2014: 'BON1', 2011: 'STIM', 2012: 'MEDI', 2013: 'SOUL', 83: 'MEGA',
  2015: 'BON2', 2018: 'ARM1', 2019: 'ARM2',
  5: 'BKEY', 13: 'RKEY', 6: 'YKEY', 40: 'BSKU', 38: 'RSKU', 39: 'YSKU',
  2022: 'PINV', 2023: 'PSTR', 2024: 'PINS', 2025: 'SUIT', 2026: 'PMAP', 2045: 'PVIS',
  // Decorations & obstacles
  2035: 'BAR1', 70: 'FCAN', 43: 'TRE1', 54: 'TRE2',
  2028: 'COLU', 85: 'TLMP', 86: 'TLP2', 34: 'CAND', 35: 'CBRA',
  44: 'TBLU', 45: 'TGRN', 46: 'TRED', 55: 'SMBT', 56: 'SMGT', 57: 'SMRT',
  48: 'ELEC', 30: 'COL1', 32: 'COL3', 31: 'COL2', 33: 'COL4',
  36: 'COL5', 37: 'COL6', 47: 'SMIT', 41: 'CEYE', 42: 'FSKU',
  // Gore
  10: 'POL5', 12: 'POL5', 24: 'POL5', 27: 'POL4', 28: 'POL2', 29: 'POL3',
  25: 'POL1', 26: 'POL6', 49: 'GOR1', 50: 'GOR2', 51: 'GOR3', 52: 'GOR4', 53: 'GOR5',
  73: 'HDB1', 74: 'HDB2', 75: 'HDB3', 76: 'HDB4', 77: 'HDB5', 78: 'HDB6', 79: 'POB1',
  15: 'PLAYN', 18: 'POSSL', 19: 'SPOSL', 20: 'TROOM', 21: 'SARGN', 22: 'HEADL', 23: 'SKULK',
  14: 'TFOG', 88: 'BBRN', 89: 'BOSF', 87: 'FIRE',
};

export const FLAG_BITS = [
  { bit: 1,  label: 'Impassable' },
  { bit: 4,  label: 'Two-Sided'  },
  { bit: 16, label: 'Upper Unpeg'},
  { bit: 32, label: 'Lower Unpeg'},
] as const;
